---
name: "tagged-release"

#
# Tag anything released to main and create a GitHub release for it.
#

on:
  push:
    branches:
      - main

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: get version number and commit message
        run: echo "CURRVER=$(cat VERSION)" >> $GITHUB_ENV

      - name: Create and push tag
        if: ${{ env.CURRVER != '0.0.0' }}
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          custom_tag: ${{ env.CURRVER }}
          tag_prefix: "v"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        if: ${{ env.CURRVER != '0.0.0' }}
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.CURRVER }}
          body: ${{ steps.tag_version.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
